sudo: false
language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
install:
  - pip install mock>=1.3.0 flake8 nose>=1.3.0 coverage coveralls
  - pip install -U setuptools
  - python setup.py install
  - pip install -r requirements/docs.txt
script:
  - flake8 .
  - python setup.py nosetests
  - python setup.py build_sphinx
after_success:
  coveralls
